version: "3"
services:
  db:
    container_name: "database"
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
  server:
    container_name: "server"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
#    Volumes conflict with coverage files from nyc
    volumes:
      - ./src:/usr/app/src
    env_file:
      - '.env.local'
    depends_on:
      - db
